let = facebookFriends{
    "listOfFriends": [
        { "name": "József Ecseki" },
        { "name": "Katalin David" },
        { "name": "Boglárka Lukáts" },
        { "name": "Zoltán Márton" },
        { "name": "Szabolcs Lakatos" },
        { "name": "Shanel Kristóf" },
        { "name": "Gyuszi Bódi" },
        { "name": "Eszter Tiringer" },
        { "name": "Dóri Kökény" },
        { "name": "Vivi Agárdi" },
        { "name": "Zoltán Samu" },
        { "name": "Kokány Vivien Gréta" },
        { "name": "Gecő Afroditte" },
        { "name": "Andrea Fekecs" },
        { "name": "Pozsár Noemi" },
        { "name": "Zsuzsa Puskás" },
        { "name": "Alexandra Hab" },
        { "name": "Brigi Némethné Kiss-Vámosi" },
        { "name": "Czekus Dorottya" },
        { "name": "Hanusz Tamás" },
        { "name": "Richárd G. Solymosi" },
        { "name": "Dóri Szkladányi" },
        { "name": "Vanessza Bianka Szabó" },
        { "name": "Roland Mándoki" },
        { "name": "Kiara Sebesi" },
        { "name": "Bíró Levi" },
        { "name": "Bernadett Wágner" },
        { "name": "Petra Szkladányi" },
        { "name": "Tomi Gubik" },
        { "name": "Erika Nyulasi" },
        { "name": "Tibor Bankó" },
        { "name": "Pálné Wrzava" },
        { "name": "Réka Kaszás" },
        { "name": "Regina Fejes" },
        { "name": "Reka Keresztes" },
        { "name": "Méhn Melinda" },
        { "name": "Hlavaj Dóri" },
        { "name": "László Bodó" },
        { "name": "Tóth Lacóó" },
        { "name": "Christiaan J. Peters" },
        { "name": "Bernadett Király" },
        { "name": "Horváth Márton" },
        { "name": "Szilagyi Tamas" },
        { "name": "Bálint Juhász" },
        { "name": "Ádám Nagy" },
        { "name": "Nikolett Hartai" },
        { "name": "Dorka Sallai" },
        { "name": "Tamara Juhász" },
        { "name": "Sarkadi Barnabás" },
        { "name": "Éva Urbán" },
        { "name": "Barnabás Rácz" },
        { "name": "Levi Lipcsei" },
        { "name": "Szampiás Zoltán" },
        { "name": "Pál Istók" },
        { "name": "Eloise Debono" },
        { "name": "Zsolt Kámán" },
        { "name": "István Milihovszki" },
        { "name": "Tamás Furkó" },
        { "name": "Kiss Gergely" },
        { "name": "Józsefné Kati Spekker" },
        { "name": "Balázs Nagy" },
        { "name": "Kámán-Tompek Nikolett" },
        { "name": "Abigél Bajó" },
        { "name": "Viktória Müller" },
        { "name": "Barna Krajcsovich" },
        { "name": "Alexandra Belovics" },
        { "name": "Soma Sáhó" },
        { "name": "Vivien Vincze" },
        { "name": "Csordás Flóra" },
        { "name": "József Spekker" },
        { "name": "Balázs Csete" },
        { "name": "Laura Dancsák" },
        { "name": "Péter Becsei" },
        { "name": "János Nóvé" },
        { "name": "András Páli" },
        { "name": "Márton Keczkó" },
        { "name": "Enikő Páli-Vejmola" },
        { "name": "Nóra Faggyas" },
        { "name": "Kator Katalin" },
        { "name": "Attila Kőrösi" },
        { "name": "Éva Bosányi" },
        { "name": "Éva Köbölné Hilarion" },
        { "name": "Veresné Vezér Olga" },
        { "name": "Mária Huszár" },
        { "name": "Istvan Simon" },
        { "name": "Luca Nagy" },
        { "name": "Akos Porcs-Makkay" },
        { "name": "Miskei Roxána" },
        { "name": "Szilvia Salzmann" },
        { "name": "Gergely Fogarasi" },
        { "name": "Márti Dömsödi" },
        { "name": "Buda Roland" },
        { "name": "Király Dávid" },
        { "name": "Tundee Thomas" },
        { "name": "Varsányi Bence" },
        { "name": "Orvos Brendon" },
        { "name": "Tibor Gősi" },
        { "name": "Faludy Zsanett" },
        { "name": "Erőssné Makovecz Ildikó" },
        { "name": "Krisztián Kupai" },
        { "name": "Anikó Péter" },
        { "name": "Gábor Németh" },
        { "name": "Borka Skrapits" },
        { "name": "Viktória Zelényi" },
        { "name": "Jana Voros" },
        { "name": "Eleni Georgopulosz" },
        { "name": "Bogi Tóth-Szabó" },
        { "name": "Katica Hunyadi" },
        { "name": "Istvánné Deme" },
        { "name": "Ruben Bajó" },
        { "name": "Márk Polákovits" },
        { "name": "Döme Rozsnyói" },
        { "name": "Dina Naszvadi" },
        { "name": "Anna Madar" },
        { "name": "Balás Fanni" },
        { "name": "Gábor Karacs" },
        { "name": "Gábor Kovács" },
        { "name": "Gabriella Szabó" },
        { "name": "Szentes Anna" },
        { "name": "Péter Tóth" },
        { "name": "Dávid Danyi" },
        { "name": "Kristóf Deli" },
        { "name": "Bálint Horváth" },
        { "name": "Anka Fehér" },
        { "name": "Pencz Attila Tamás" },
        { "name": "Michael Ru" },
        { "name": "Attila Juhász" },
        { "name": "Renátó Hegedűs" },
        { "name": "Ráduly István" },
        { "name": "Enikő Ücveges" },
        { "name": "Orsolya Berecz" }
      ]
    }